**导入pytorch库**

In [6]:
import torch
import numpy as np

**直接从数据创建张量**

In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**从numpy数组创建张量**

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


**从另一个张量创建张量.** 
- 除非显式覆盖，否则新张量将保留参数张量的属性（形状、数据类型）。

In [9]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1018, 0.4835],
        [0.7215, 0.0749]]) 



**使用随机值或常量值**
- shape 是张量维度的元组。在以下函数中，它决定了输出张量的维度。

In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0451, 0.7728, 0.4617],
        [0.7551, 0.2397, 0.8228]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**张量的属性（attributes of tensor）**
- 张量属性描述了它们的形状、数据类型以及存储它们的设备。




In [11]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**张量的操作（Operations on Tensors）**
- 这里全面介绍了 100 多种张量运算，包括算术运算、线性代数、矩阵操作（转置、索引、切片）、采样等。https://docs.pytorch.org/docs/stable/torch.html
- Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.
- By default, tensors are created on the CPU. **We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability).**
- Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [13]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

**标准的numpy-like的索引与切片** Standard numpy-like indexing and slicing

In [14]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**连接张量** 
- 你可以使用 `torch.cat` 沿着给定维度连接一系列张量。
- 另请参阅 `torch.stack` ，这是另一个与 `torch.cat` 略有不同的张量连接操作

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim 改成0试试
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
